Get a pretty printout

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -34,5 +34,12 @@ jobs:
       working-directory: ${{github.workspace}}/build
       # Execute tests defined by the CMake configuration.
       # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
-      run: ctest -C ${{env.BUILD_TYPE}}
-
+      run: ctest -C ${{env.BUILD_TYPE}} --output-junit ctest-results.xml
+    
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()      # run this step even if previous step failed
+      with:
+        name: JEST Tests              # Name of the check run which will be created
+        path: build/ctest-results.xml # Path to test results
+        reporter: jest-junit          # Format of test results
