yatr yet another test reporter

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -39,9 +39,14 @@ jobs:
         ls -lAh ${{github.workspace}}/build
     
     - name: Test Report
-      uses: dorny/test-reporter@v1
-      if: success() || failure()      # run this step even if previous step failed
+      uses: phoenix-actions/test-reporting@v8
+      id: test-report               # Set ID reference for step
+      if: success() || failure()    # run this step even if previous step failed
       with:
-        name: JEST Tests              # Name of the check run which will be created
-        path: ${{github.workspace}}/build/ctest-results.xml # Path to test results
-        reporter: jest-junit          # Format of test results
+        name: JEST Tests            # Name of the check run which will be created
+        path: ${{github.workspace}}/build/*.xml    # Path to test results
+        reporter: jest-junit        # Format of test results
+
+    - name: Read output variables
+      run: |
+        echo "url is ${{ steps.test-report.outputs.runHtmlUrl }}"
